[project]
name = "escrow"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
fuels = "0.31.1"
fuels-abigen-macro = "0.31.1"
rand = "0.5"
tokio = { version = "1.22", features = ["rt", "macros"] }

[[test]]
harness = true
name = "tests"
path = "tests/harness.rs"